version: '3'
services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - gettrip-backend
  
  webapp:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - gettrip-backend

networks:
  gettrip-backend:
