"""

Revision ID: b212c2faf53d
Revises: 33b88cf38af4
Create Date: 2022-04-06 21:03:59.412588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b212c2faf53d'
down_revision = '33b88cf38af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'duration',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('places', 'duration',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
